### PR TITLE
Fix test container name

### PR DESCRIPTION
**Pull request by BHodl**
Proposed fix for issue #250

### CODE REVIEW

**Comment by Kexkey** [comment]
So if you could just use the name: fix I described in the issue, that would be cleaner.  I'm ok with not displaying verbose stuff from the tests though, good thing you removed them.

Are you willing to make a PR in the cypherapps repo for the other fix I described in the issue?

Thanks so much!!

**Comment by Kexkey** [comment]
So if you could just use the name: fix I described in the issue, that would be cleaner.  I'm ok with not displaying verbose stuff from the tests though, good thing you removed them.

Are you willing to make a PR in the cypherapps repo for the other fix I described in the issue?

Thanks so much!!

**Comment by BHodl** [comment]
Yes I will fix it this way then, and fix cypherapps. And yes I use docker-compose.
Thanks!

**Comment by Kexkey** [comment]
It looks like `name` is not allowed in Swarm mode:

```
(root) Additional property name is not allowed
```

You will have to add the `<% if ( docker_mode !== 'swarm' ) { %>` condition in the docker-compose.yaml template...

**Comment by Kexkey** [comment]
It looks like `name` is not allowed in Swarm mode:

```
(root) Additional property name is not allowed
```

You will have to add the `<% if ( docker_mode !== 'swarm' ) { %>` condition in the docker-compose.yaml template...

**Comment by Kexkey** [comment]
haha you're fast!

**Comment by Kexkey** [comment]
haha you're fast!

**Comment by Kexkey** [comment]
Awesome!  This will be part of the next minor release, v0.8.1.  You made me check some other stuff as well and found that there are problems with the tests (in proxy_docker/app/tests/) when using docker-compose... I fixed them.

Thanks again!

**Comment by BHodl** [comment]
Not so fast, I did't had time to test in my lab, just finished the test and get an error preventing cyphernode to start properly. 
`ERROR: The Compose file '/home/user/Workspace/cyphernode/dist/docker-compose.yaml' is invalid because:
'name' does not match any of the regexes: '^x-'
`

**Comment by BHodl** [comment]
docker-compose version 1.29.2

**Comment by BHodl** [comment]
Adding `-p cyphernode` to docker-compose in start.sh script (line 69) is a better fix, at least it work for me.

**Comment by BHodl** [comment]
Check #253

**Comment by Kexkey** [comment]
Yeah I got that error on my Mac but then I upgraded docker-compose and the error went away.  But your new PR is much better, good call!

**Pull request merged**
