### PR TITLE
Update README.MD

### PR DESCRIPTION
**Pull request by MagicFab**
Typos, re-wording in some paragraphs, requirements section (WIP), see #40

### CODE REVIEW

**Comment by MagicFab** [comment]
Can't share this project much until it has clear requirements. Is there any blocker I can help with ?

**Comment by MagicFab** [comment]
CC @Kexkey

**Comment by MagicFab** [comment]
I am told by @Kexkey that CN runs on a rPi2 w/8GB SD card in prune mode. Is this the standard configuration ATM ? Id'rather have a minimal viable environment on safer storage than depend on 8 GB SD. @kexkey even then wouldn't prune mode still mean having a full node first ?
For the record other readers can check [What is the prune mode exactly ?](https://www.reddit.com/r/Bitcoin/comments/5ywru2/what_is_the_prune_mode_exactly/) and [How can I run bitcoind in pruning mode?](https://bitcoin.stackexchange.com/questions/37496/how-can-i-run-bitcoind-in-pruning-mode).

**Comment by Kexkey** [comment]
There's no "standard" configuration.  You're right, standard SD cards are easily corrupted, I usually prefer mounting combined USB sticks (using LVM2 or better) for the data I don't want to lose.  On a VM, I use mounted volumes instead of the VM fs, easier to backup.

Validate the whole blockchain on a RPi takes a long time, but it works.  I usually copy my existing data from current nodes I have.

A prune node is a full node.  It only doesn't keep historical data from the start, but it validates everything from the genesis block.  It usually is a good tradeoff space/functionality, but getrawtransaction on old txs won't work.  The fees calculation needs previous tx (outpoint in input) but if it is an old tx, we can't get it.  The fees will be null.

**Comment by Kexkey** [comment]
We haven't tested Cyphernode on Windows.  But we heard Windows 10 now supports Linux with an optional pack or something...

We tested on ARM, x86, OSX, Debian flavors including Raspbian... it should work on most of the platforms supported by Docker.

**Comment by Kexkey** [comment]
Cyphernode needs very small amount of RAM and CPU, except when Bitcoin Core is syncing.

docker stats on a RPi:
screen shot 2019-01-30 at 8 06 25 am

docker stats on a small debian instance on lunanode (5$/month):
screen shot 2019-01-30 at 8 07 05 am

docker stats on a Mac Mini:
screen shot 2019-01-30 at 8 14 22 am

**Comment by Kexkey** [comment]
Important note: the Lightning node officially doesn't support dealing with a prune Bitcoin node.  But in fact, if pruning is not too small and the LN node doesn't have to getblock before the threshold, it works well.

**Comment by Kexkey** [comment]
Also: depending of the optional features installed, the requirements will change.  For example, we are working on an indexer (for an explorer) that will add disk space requirement.  During indexing, the CPU and disk IO are solicited the same way it is when Bitcoin Core syncs.

Another example is the grafana optional feature that requires more CPU and RAM when it is actually used.

The minimum requirements are based on the actual configuration of cyphernode.  I guess it is a good idea to specify what's required during the installation process.  Thanks for the idea!

cc: @schulterklopfer what do you think?

**Comment by schulterklopfer** [comment]
ACK ;-)

**Comment by MagicFab** [comment]
Any progress on this ? I thought contributing to improving the docs would be an easy start.

**Comment by Kexkey** [comment]
I merged it to dev branch by cherry-picking the commit.  It will be part of the v0.2.0 release.  Thanks @MagicFab

**Pull request closed without merging**
