### PR TITLE
Features/minor changes

### PR DESCRIPTION
**Pull request by schulterklopfer**

### CODE REVIEW

**Comment by Kexkey** [comment]
I see there is still the install/ folder in the PR, can you rebase on dev where install/ has been removed... thanks!

**Comment by Kexkey** [comment]
Lightning Node and Opentimestamps client are deactivated on the welcome page.  But they are running correctly.

**Comment by Kexkey** [comment]
File not found when I click on links to download config or keys.

**Comment by schulterklopfer** [comment]
lol shit! :O :D

**Comment by schulterklopfer** [comment]
@Kexkey if you build welcome_app from dev and tag it with version 0.3.0 (major changes) and then checkout the dev branch of cypherapps it should work nicely together with this PR and the errors should be hopefuly gone.

**Comment by Kexkey** [comment]
lgtm, needs a rebase and I'll merge to dev

**Comment by schulterklopfer** [comment]
rebase done :)

**Pull request merged**
