### PR TITLE
Adding a link, should add more

### PR DESCRIPTION
**Pull request by dbolser**
The best way to compete is to collaborate :-)

### CODE REVIEW

**Comment by dbolser** [comment]
Is this the right branch?

**Comment by schulterklopfer** [comment]
no SEO boost for projects we don't support

**Comment by dbolser** [comment]
Backwards thinking

**Comment by FrancisPouliot** [comment]
Agree with SKP. We wouldn't want someone accidentally clicking on this link

**Comment by dbolser** [comment]
Yeah sure, that's exactly the kind of moron you want to keep on your
project right?

Either don't mention those projects at all, or link then correctly please.
Mentioning but not linking is idiotic.

Happy to submit PRs with links.

**Comment by FrancisPouliot** [comment]
We mention it so that people who already know about bitcore will know it's a replacement. Its a terrible project.

**Pull request closed without merging**
