### PR TITLE
Releases/v0.8.0 fix test monitor

### PR DESCRIPTION
**Pull request by BHodl**
Better working fix for test monitor

### CODE REVIEW

**Comment by Kexkey** [comment]
I think we should add `-p $APP_ID` in `start_apps()`

What do you think?

**Comment by Kexkey** [comment]
Oh by default docker-compose will use the dir name as the project name, and APP_ID is the dir name, so it won't change anything.  But I still think we should add it, if in the future APP_ID is not necessarily the dir name, it will already be set correctly.

**Comment by BHodl** [comment]
... with docker-compose.

**Comment by Kexkey** [comment]
Awesome, thanks!

**Pull request merged**
