### PR TITLE
Moved env variables out of docker-compose.yaml

### PR DESCRIPTION
**Pull request by filecommander**
Copied what was done with proxycron in previous version of CN

### CODE REVIEW

**Comment by Kexkey** [comment]
I ran setup and on start:

```
kexkey@OneMoreBoosterPlease dist % ./start.sh 

'Run as another user' feature is not supported on OSX.  User kexkey will be used to run Cyphernode.

open /Users/kexkey/dev/cn-dev2/dist/.env/proxy.env: no such file or directory

```

It looks like proxy.env was not generated.  I'll investigate a bit...

**Comment by Kexkey** [comment]
I think you forgot to copy the .env files, in setup.sh.  The same way you copied proxycron.env in the previous PR:

```
copy_file $cyphernodeconf_filepath/proxycron/proxycron.env ${current_path}/.env/proxycron.env 1 $SUDO_REQUIRED
```

We need all of the generated .env files to be copied to the deployment dirs.

**Comment by filecommander** [comment]
My error not committing the setup.sh

**Comment by Kexkey** [comment]
LGTM!  Thanks!!

**Pull request merged**
